
server:
  port: ${port}      # 绑定应用服务端口

spring:
  application:
    name: mall-eureka-node     # 指定应用名,也就是注册中心显示的名称

eureka:
  instance:
    ip-address: 127.0.0.1      # 绑定ip地址
#    prefer-ip-address: true    # 将自己的ip地址注册到Eureka中心
#  server:
#    enable-self-preservation: false    # 禁用自我保护模式，就是心跳机制。默认开启
#    eviction-interval-timer-in-ms: 60000   # 清理间隔：单位毫秒，默认60*1000
  client:
    register-with-eureka: true     # 是否将自身注册到Eureka中
    fetch-registry: true            # 是否需要从Eureka中获取注册的信息
    service-url:
      defaultZone: ${eureka.url}    # Eureka交互地址，注册中心的地址



