apollo:
  bootstrap:
    enabled: true   #开启Apollo
  cacheDir: D:\\Apollo\\opt\\data   #自定义配置文件的缓存目录
  namespaces: application

server:
  port: ${port}

spring:
  application:
    name: mall-user
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: ${mysql.url}
        username: ${mysql.username}
        password: ${mysql.password}
  sleuth:
    sampler:
      probability: ${sleuth.sampler.probability}
    web:
      client:
        enabled: true
  zipkin:
    base-url: ${zipkin.base.url}
    sender:
      type: web   # 有kafka web rabbit mq三种选择,注意这里不用Apollo配置，因为会被先解析成默认rabbit方式
    enabled: true

mybatis:
  type-aliases-package: com.xc.mall.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.xc.mapper : debug

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.defaultZone}
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-read-timeout-seconds: 8



