
server:
  port: 10060

spring:
  application:
    name: zipkin-server
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:10086/eureka/
    instance:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
