
server:
  port: 10060
  servlet:
    context-path: /zipkin
spring:
  application:
    name: zipkin-server
  zipkin:
    base-url: http://127.0.0.1:10060/zipkin
  main:
    allow-bean-definition-overriding: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false
