apollo:
  bootstrap:
    enabled: true   #开启Apollo
  cacheDir: D:\\Apollo\\opt\\data   #自定义配置文件的缓存目录
  namespaces: application
  ## meta: http://127.0.0.1:8070

server:
  port: ${app.port}   # 使用placeholder来进行数值注入
spring:
  application:
    name: ${app.name}
  sleuth:
    sampler:
      probability: ${sleuth.sampler.probability}    # 采集量：0~100%(1为100%)
    web:
      client:
        enabled: true
  zipkin:
    base-url: ${zipkin.base.url}    # zipkin服务器的注册地址
    sender:
      type: web   # 有kafka web rabbit mq三种选择,注意这里不用Apollo配置，因为会被先解析成默认rabbit方式
    enabled: true     # 开启zipkin客户端连接

eureka:
  client:
    service-url:
      defaultZone: ${app.defaultZone}