apollo:
  bootstrap:
    enabled: true   #开启Apollo
  cacheDir: D:\\Apollo\\opt\\data   #自定义配置文件的缓存目录
  namespaces: application
  ## meta: http://127.0.0.1:8070

server:
  port: ${app.port}   # 使用placeholder来进行数值注入
spring:
  application:
    name: ${app.name}
eureka:
  client:
    service-url:
      defaultZone: ${app.defaultZone}